"use client";

import { useEffect, useMemo, useState } from "react";
import { Archive, CheckCircle2, ClipboardList, Download, FileUp, Filter, Flag, Plus, Search, ShieldCheck, Sparkles, Trash2, X } from "lucide-react";

type EvidenceLevel="Supported"|"Probable"|"Possible"|"Unverified"|"Disproved";
type Evidence={id:string;claim:string;person:string;level:EvidenceLevel;source:string;recordType:string;date:string;notes:string;createdAt:string};
type LogEntry={id:string;question:string;repository:string;search:string;result:string;next:string;createdAt:string};
type TimelineEvent={id:string;person:string;date:string;event:string;place:string;source:string};
const LEVELS:EvidenceLevel[]=["Supported","Probable","Possible","Unverified","Disproved"];

const read=(key:string)=>{try{return JSON.parse(localStorage.getItem(key)||"[]")}catch{return[]}};
const write=(key:string,value:any)=>localStorage.setItem(key,JSON.stringify(value));

export default function ResearchCommandCenter(){
 const [tab,setTab]=useState<"overview"|"evidence"|"log"|"timeline">("overview");
 const [evidence,setEvidence]=useState<Evidence[]>([]);
 const [logs,setLogs]=useState<LogEntry[]>([]);
 const [timeline,setTimeline]=useState<TimelineEvent[]>([]);
 const [search,setSearch]=useState("");
 const [level,setLevel]=useState<"All"|EvidenceLevel>("All");
 const [claim,setClaim]=useState("");const [person,setPerson]=useState("");const [source,setSource]=useState("");const [recordType,setRecordType]=useState("Original record");const [evLevel,setEvLevel]=useState<EvidenceLevel>("Unverified");const [notes,setNotes]=useState("");
 const [question,setQuestion]=useState("");const [repository,setRepository]=useState("");const [searchDone,setSearchDone]=useState("");const [result,setResult]=useState("");const [next,setNext]=useState("");
 const [eventPerson,setEventPerson]=useState("");const [eventDate,setEventDate]=useState("");const [eventName,setEventName]=useState("");const [eventPlace,setEventPlace]=useState("");const [eventSource,setEventSource]=useState("");
 useEffect(()=>{setEvidence(read("gg-evidence-vault"));setLogs(read("gg-research-log"));setTimeline(read("gg-timeline"))},[]);
 const saveEvidence=()=>{if(!claim.trim())return;const item:Evidence={id:"EVID-"+String(evidence.length+1).padStart(4,"0"),claim:claim.trim(),person:person.trim(),level:evLevel,source:source.trim(),recordType,date:new Date().toLocaleDateString(),notes:notes.trim(),createdAt:new Date().toISOString()};const next=[item,...evidence];setEvidence(next);write("gg-evidence-vault",next);setClaim("");setPerson("");setSource("");setNotes("")};
 const saveLog=()=>{if(!question.trim())return;const item:LogEntry={id:crypto.randomUUID(),question:question.trim(),repository:repository.trim(),search:searchDone.trim(),result:result.trim(),next:next.trim(),createdAt:new Date().toISOString()};const n=[item,...logs];setLogs(n);write("gg-research-log",n);setQuestion("");setRepository("");setSearchDone("");setResult("");setNext("")};
 const saveEvent=()=>{if(!eventDate.trim()||!eventName.trim())return;const item:TimelineEvent={id:crypto.randomUUID(),person:eventPerson.trim(),date:eventDate.trim(),event:eventName.trim(),place:eventPlace.trim(),source:eventSource.trim()};const n=[...timeline,item].sort((a,b)=>a.date.localeCompare(b.date));setTimeline(n);write("gg-timeline",n);setEventPerson("");setEventDate("");setEventName("");setEventPlace("");setEventSource("")};
 const removeEvidence=(id:string)=>{const n=evidence.filter(x=>x.id!==id);setEvidence(n);write("gg-evidence-vault",n)};
 const removeLog=(id:string)=>{const n=logs.filter(x=>x.id!==id);setLogs(n);write("gg-research-log",n)};
 const removeEvent=(id:string)=>{const n=timeline.filter(x=>x.id!==id);setTimeline(n);write("gg-timeline",n)};
 const filtered=evidence.filter(e=>(level==="All"||e.level===level)&&[e.claim,e.person,e.source,e.recordType].join(" ").toLowerCase().includes(search.toLowerCase()));
 const counts=useMemo(()=>Object.fromEntries(LEVELS.map(l=>[l,evidence.filter(e=>e.level===l).length])) as Record<EvidenceLevel,number>,[evidence]);
 const exportCenter=()=>{const blob=new Blob([JSON.stringify({evidence,logs,timeline,exportedAt:new Date().toISOString()},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="genealogy-guide-research-center.json";a.click();URL.revokeObjectURL(a.href)};
 return <div className="researchCommandCenter">
  <div className="rccHeader"><div><p className="eyebrow">RESEARCH COMMAND CENTER</p><h3>Your evidence, questions, and timeline in one place.</h3><p>Local-first research workspace. Nothing here upgrades a claim automatically—your evidence level stays under your control.</p></div><button className="secondary" onClick={exportCenter}><Download size={15}/> Export research</button></div>
  <div className="rccTabs">{[["overview","Overview"],["evidence","Evidence Vault"],["log","Research Log"],["timeline","Timeline"]].map(([k,v])=><button className={tab===k?"active":""} onClick={()=>setTab(k as any)} key={k}>{v}</button>)}</div>
  {tab==="overview"&&<><div className="rccStats"><div><strong>{evidence.length}</strong><span>evidence items</span></div><div><strong>{logs.length}</strong><span>research searches</span></div><div><strong>{timeline.length}</strong><span>timeline events</span></div><div><strong>{counts.Supported}</strong><span>supported claims</span></div></div><div className="rccGrid"><article><ShieldCheck/><h4>Evidence firewall</h4><p>Kinley and your tree should distinguish Supported, Probable, Possible, Unverified, and Disproved. A missing generation stays missing until evidence closes it.</p></article><article><Flag/><h4>Contradiction radar</h4><p>Use the timeline and evidence records to spot impossible ages, overlapping residences, duplicate identities, and conflicting dates.</p></article><article><ClipboardList/><h4>Research discipline</h4><p>Log negative searches too. “Not found” is useful when you record the jurisdiction, collection, date range, and search method.</p></article></div><div className="rccQuick"><button onClick={()=>setTab("evidence")}><Plus size={16}/> Add evidence</button><button onClick={()=>setTab("log")}><Search size={16}/> Log a search</button><button onClick={()=>setTab("timeline")}><Sparkles size={16}/> Add timeline event</button></div></>}
  {tab==="evidence"&&<><div className="rccForm"><h4>Add Evidence</h4><input value={claim} onChange={e=>setClaim(e.target.value)} placeholder="Claim this evidence relates to"/><div className="rccFormGrid"><input value={person} onChange={e=>setPerson(e.target.value)} placeholder="Person"/><input value={source} onChange={e=>setSource(e.target.value)} placeholder="Source title / citation"/><select value={recordType} onChange={e=>setRecordType(e.target.value)}><option>Original record</option><option>Derivative record</option><option>Authored work</option><option>Family testimony</option><option>Online tree</option><option>DNA evidence</option></select><select value={evLevel} onChange={e=>setEvLevel(e.target.value as EvidenceLevel)}>{LEVELS.map(x=><option key={x}>{x}</option>)}</select></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What does this source actually prove? What does it not prove?"/><button className="primary" onClick={saveEvidence}><Archive size={16}/> Save EVID-{String(evidence.length+1).padStart(4,"0")}</button></div><div className="rccFilters"><div className="rccSearch"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search evidence"/></div><select value={level} onChange={e=>setLevel(e.target.value as any)}><option>All</option>{LEVELS.map(x=><option key={x}>{x}</option>)}</select><Filter size={15}/></div><div className="evidenceVaultList">{filtered.map(e=><article key={e.id}><div className="evidenceId">{e.id}</div><div className="evidenceMain"><strong>{e.claim}</strong><span>{e.person||"Person not specified"} • {e.recordType} • {e.source||"Source not entered"}</span><p>{e.notes||"No notes yet."}</p></div><div className={"evidenceLevel "+e.level.toLowerCase()}>{e.level}</div><button className="iconDanger" onClick={()=>removeEvidence(e.id)} aria-label={"Delete "+e.id}><Trash2 size={15}/></button></article>)}{filtered.length===0&&<div className="rccEmpty">No evidence matches this filter.</div>}</div></>}
  {tab==="log"&&<><div className="rccForm"><h4>Log a Research Search</h4><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Research question"/><div className="rccFormGrid"><input value={repository} onChange={e=>setRepository(e.target.value)} placeholder="Repository / archive / website"/><input value={searchDone} onChange={e=>setSearchDone(e.target.value)} placeholder="Collection, terms, date range"/></div><textarea value={result} onChange={e=>setResult(e.target.value)} placeholder="Result: what did you find or fail to find?"/><textarea value={next} onChange={e=>setNext(e.target.value)} placeholder="Next step / record to search next"/><button className="primary" onClick={saveLog}><CheckCircle2 size={16}/> Save research log</button></div><div className="rccList">{logs.map(l=><article key={l.id}><div><strong>{l.question}</strong><span>{l.repository||"Repository not entered"} • {new Date(l.createdAt).toLocaleDateString()}</span><p><b>Search:</b> {l.search||"—"}<br/><b>Result:</b> {l.result||"—"}<br/><b>Next:</b> {l.next||"—"}</p></div><button className="iconDanger" onClick={()=>removeLog(l.id)} aria-label="Delete research log"><Trash2 size={15}/></button></article>)}</div></>}
  {tab==="timeline"&&<><div className="rccForm"><h4>Add Timeline Event</h4><div className="rccFormGrid"><input value={eventPerson} onChange={e=>setEventPerson(e.target.value)} placeholder="Person"/><input value={eventDate} onChange={e=>setEventDate(e.target.value)} placeholder="Date / year"/><input value={eventName} onChange={e=>setEventName(e.target.value)} placeholder="Event (birth, marriage, residence...)"/><input value={eventPlace} onChange={e=>setEventPlace(e.target.value)} placeholder="Place"/></div><input value={eventSource} onChange={e=>setEventSource(e.target.value)} placeholder="Source / citation"/><button className="primary" onClick={saveEvent}><Plus size={16}/> Add timeline event</button></div><div className="timelineList">{timeline.map(e=><article key={e.id}><time>{e.date}</time><div><strong>{e.event}</strong><span>{e.person||"Person"}{e.place?" • "+e.place:""}</span><small>{e.source||"No source attached"}</small></div><button className="iconDanger" onClick={()=>removeEvent(e.id)} aria-label="Delete timeline event"><Trash2 size={15}/></button></article>)}</div></>}
 </div>
}
