"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Pause, Play, Plus, RotateCcw, Search, ShieldCheck, SkipBack, SkipForward, X } from "lucide-react";
import "./migration.css";

type Stop={id:string;person:string;year:number;place:string;lat:number;lon:number;confidence:"Documented"|"Probable"|"Possible";source:string;notes:string};

const demo:Stop[]=[
 {id:"1",person:"Ancestor A",year:1820,place:"Oglethorpe County, Georgia",lat:33.88,lon:-83.44,confidence:"Documented",source:"Example census record",notes:"Use this as a template. Replace with your own source-backed location."},
 {id:"2",person:"Ancestor A",year:1845,place:"Madison County, Georgia",lat:34.13,lon:-83.20,confidence:"Documented",source:"Example land record",notes:"The map shows documented endpoints, not an invented route."},
 {id:"3",person:"Ancestor A",year:1870,place:"Cabarrus County, North Carolina",lat:35.41,lon:-80.58,confidence:"Probable",source:"Example census record",notes:"Verify the jurisdiction and identity before treating this move as established."},
];

export default function MigrationMap(){
 const [stops,setStops]=useState<Stop[]>(demo);
 const [year,setYear]=useState(1820); const [playing,setPlaying]=useState(false); const [selected,setSelected]=useState<Stop|null>(null); const [person,setPerson]=useState("All ancestors"); const [showAdd,setShowAdd]=useState(false);
 const [draft,setDraft]=useState({person:"",year:"",place:"",lat:"",lon:"",confidence:"Documented" as Stop["confidence"],source:"",notes:""});
 const people=useMemo(()=>["All ancestors",...Array.from(new Set(stops.map(s=>s.person)))],[stops]);
 const filtered=useMemo(()=>stops.filter(s=>person==="All ancestors"||s.person===person).sort((a,b)=>a.year-b.year),[stops,person]);
 const years=filtered.map(s=>s.year); const min=Math.min(...years,1820),max=Math.max(...years,1870);
 useEffect(()=>{if(!playing)return;const t=setInterval(()=>setYear(y=>y>=max?(setPlaying(false),max):y+1),80);return()=>clearInterval(t)},[playing,max]);
 const visible=filtered.filter(s=>s.year<=year); const latest=visible.at(-1);
 const add=()=>{if(!draft.person||!draft.year||!draft.place||!draft.lat||!draft.lon||!draft.source)return;setStops(s=>[...s,{id:crypto.randomUUID(),person:draft.person,year:Number(draft.year),place:draft.place,lat:Number(draft.lat),lon:Number(draft.lon),confidence:draft.confidence,source:draft.source,notes:draft.notes}]);setShowAdd(false);setDraft({person:"",year:"",place:"",lat:"",lon:"",confidence:"Documented",source:"",notes:""})};
 const reset=()=>setYear(min);
 return <main className="migrationPage"><header className="migrationHeader"><a href="/" className="back"><ArrowLeft size={16}/> Genealogy Guide</a><div><p className="eyebrow">MIGRATION MAP</p><h1>Watch the family move through time.</h1><p>Animate documented locations across generations. The map never invents a route between two records.</p></div><button className="primary" onClick={()=>setShowAdd(true)}><Plus size={16}/> Add location</button></header>
 <section className="mapToolbar"><label>Ancestor <select value={person} onChange={e=>{setPerson(e.target.value);setYear(min)}}>{people.map(p=><option key={p}>{p}</option>)}</select></label><div className="controls"><button onClick={reset}><RotateCcw size={15}/> Reset</button><button onClick={()=>setYear(Math.max(min,year-1))}><SkipBack size={15}/></button><button className="play" onClick={()=>setPlaying(!playing)}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?"Pause":"Play"}</button><button onClick={()=>setYear(Math.min(max,year+1))}><SkipForward size={15}/></button></div></section>
 <section className="mapShell"><div className="mapStage"><div className="mapGrid"/><div className="continent"/><div className="routeLayer">{visible.slice(1).map((s,i)=>{const a=visible[i];return <div key={s.id} className="route" style={{left:`${18+(a.lon+100)*1.9}%`,top:`${54-(a.lat-25)*2.5}%`,width:`${Math.max(5,Math.abs(s.lon-a.lon)*1.9)}%`,transform:`rotate(${Math.atan2(-(s.lat-a.lat),(s.lon-a.lon))*180/Math.PI}deg)`}}/>})}</div>{visible.map(s=><button key={s.id} className={`pin ${s.confidence.toLowerCase()}`} style={{left:`${18+(s.lon+100)*1.9}%`,top:`${54-(s.lat-25)*2.5}%`}} onClick={()=>setSelected(s)} title={s.place}><span/>{s.year}</button>)}{latest&&<div className="mapNow"><span>{latest.year}</span><strong>{latest.place}</strong></div>}</div>
 <aside className="timeline"><div className="timelineTop"><span>Timeline</span><strong>{year}</strong></div><input type="range" min={min} max={max} value={year} onChange={e=>setYear(Number(e.target.value))}/><div className="years"><span>{min}</span><span>{max}</span></div><div className="legend"><span><i className="dot documented"/> Documented</span><span><i className="dot probable"/> Probable</span><span><i className="dot possible"/> Possible</span></div></aside></section>
 <section className="migrationBottom"><div><p className="eyebrow">DOCUMENTARY TRAIL</p><h2>Every stop has a reason to exist.</h2><p>Click a location to inspect its source. A line represents chronological records, not a claim about the exact path taken between them.</p></div><div className="stopList">{filtered.map(s=><button key={s.id} onClick={()=>{setSelected(s);setYear(s.year)}}><b>{s.year}</b><span>{s.place}</span><small>{s.confidence} · {s.source}</small></button>)}</div></section>
 {selected&&<div className="modalBack" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><p className="eyebrow">LOCATION RECORD</p><h2>{selected.place}</h2><p><strong>{selected.person}</strong> · {selected.year}</p><div className="sourceBox"><ShieldCheck size={17}/><div><b>{selected.confidence}</b><span>{selected.source}</span></div></div><p>{selected.notes}</p><button className="secondary" onClick={()=>setSelected(null)}>Close</button></div></div>}
 {showAdd&&<div className="modalBack" onClick={()=>setShowAdd(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowAdd(false)}><X/></button><p className="eyebrow">NEW MAP LOCATION</p><h2>Add a documented stop.</h2><input placeholder="Person" value={draft.person} onChange={e=>setDraft({...draft,person:e.target.value})}/><input placeholder="Year" type="number" value={draft.year} onChange={e=>setDraft({...draft,year:e.target.value})}/><input placeholder="Place" value={draft.place} onChange={e=>setDraft({...draft,place:e.target.value})}/><div className="twoCol"><input placeholder="Latitude" value={draft.lat} onChange={e=>setDraft({...draft,lat:e.target.value})}/><input placeholder="Longitude" value={draft.lon} onChange={e=>setDraft({...draft,lon:e.target.value})}/></div><select value={draft.confidence} onChange={e=>setDraft({...draft,confidence:e.target.value as Stop["confidence"]})}><option>Documented</option><option>Probable</option><option>Possible</option></select><input placeholder="Source / citation" value={draft.source} onChange={e=>setDraft({...draft,source:e.target.value})}/><textarea placeholder="Notes" value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/><button className="primary full" onClick={add}>Add to map</button></div></div>}
 </main>
}
