"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Pause, Play, RotateCcw, ShieldCheck, SkipBack, SkipForward, X, MapPinned } from "lucide-react";
import { parseMigrationStops, stateAbbr, stateMapUrl, type MigrationStop, type TreePerson, type TreeRelationship } from "../lib/migration";
import "./migration.css";

type TreeSource={id:string;personId:string;title:string;type:string;date:string;url:string;notes:string};
const blankMap="https://upload.wikimedia.org/wikipedia/commons/3/30/Blank_US_Map_%28states_only%29.svg";

export default function MigrationMap(){
 const [stops,setStops]=useState<MigrationStop[]>([]);
 const [year,setYear]=useState(0); const [playing,setPlaying]=useState(false); const [selected,setSelected]=useState<MigrationStop|null>(null); const [person,setPerson]=useState("All ancestors"); const [loaded,setLoaded]=useState(false); const [treeName,setTreeName]=useState("your family"); const [mapSrc,setMapSrc]=useState(blankMap);
 useEffect(()=>{try{const saved=localStorage.getItem("gg-tree");if(!saved){setLoaded(true);return;}const data=JSON.parse(saved);const people=Array.isArray(data.people)?data.people as TreePerson[]:[];const relationships=Array.isArray(data.relationships)?data.relationships as TreeRelationship[]:[];const sources=Array.isArray(data.sources)?data.sources as TreeSource:[];setStops(parseMigrationStops(people,relationships,sources));setTreeName(people[0]?.name&&people[0].name!=="Your research starting point"?people[0].name:"your family");}catch{}finally{setLoaded(true)}},[]);
 const people=useMemo(()=>["All ancestors",...Array.from(new Set(stops.map(s=>s.person)))],[stops]);
 const filtered=useMemo(()=>stops.filter(s=>person==="All ancestors"||s.person===person).sort((a,b)=>a.year-b.year),[stops,person]);
 const years=filtered.map(s=>s.year); const min=years.length?Math.min(...years):0; const max=years.length?Math.max(...years):0;
 useEffect(()=>{if(years.length)setYear(min)},[min,person,stops.length]);
 useEffect(()=>{if(!playing)return;const t=setInterval(()=>setYear(y=>y>=max?(setPlaying(false),max):y+1),90);return()=>clearInterval(t)},[playing,max]);
 const visible=filtered.filter(s=>s.year<=year); const latest=visible.at(-1); const activeState=latest?.state||filtered.at(-1)?.state||"";
 useEffect(()=>{setMapSrc(activeState?stateMapUrl(activeState):blankMap)},[activeState]);
 const stateCount=Array.from(new Set(filtered.map(s=>s.state))).length; const ready=filtered.length>=2&&stateCount>=2;
 if(!loaded)return <main className="migrationPage"><div className="migrationLoading">Loading your family tree…</div></main>;
 if(!ready)return <main className="migrationPage"><header className="migrationHeader"><a href="/" className="back"><ArrowLeft size={16}/> Genealogy Guide</a><div><p className="eyebrow">MIGRATION MAP</p><h1>Not unlocked yet.</h1><p>Genealogy Guide needs at least two location points across at least two states before it can show a migration view.</p></div></header><section className="migrationEmpty"><MapPinned size={30}/><h2>Keep building the tree.</h2><p>Add ancestors, their locations, and the records that support those locations. When the tree shows movement across states, the Migration Map button will appear automatically.</p><a className="primary" href="/">Return to family tree</a></section></main>;
 const reset=()=>setYear(min);
 return <main className="migrationPage">
  <header className="migrationHeader"><a href="/" className="back"><ArrowLeft size={16}/> Genealogy Guide</a><div><p className="eyebrow">MIGRATION MAP • FROM YOUR TREE</p><h1>Watch {treeName} move through time.</h1><p>These locations were pulled automatically from your family tree. The map visualizes chronological evidence without inventing a travel route.</p></div><div className="treeDrivenBadge"><ShieldCheck size={15}/> Tree data only</div></header>
  <section className="mapToolbar"><label>Ancestor <select value={person} onChange={e=>{setPerson(e.target.value);setPlaying(false)}}>{people.map(p=><option key={p}>{p}</option>)}</select></label><div className="mapStats"><span><b>{filtered.length}</b> locations</span><span><b>{stateCount}</b> states</span></div><div className="controls"><button onClick={reset}><RotateCcw size={15}/> Reset</button><button onClick={()=>setYear(Math.max(min,year-1))}><SkipBack size={15}/></button><button className="play" onClick={()=>setPlaying(!playing)}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?"Pause":"Play"}</button><button onClick={()=>setYear(Math.min(max,year+1))}><SkipForward size={15}/></button></div></section>
  <section className="mapShell"><div className="mapStage"><div className="mapBackdrop"/><img className="stateMapImage" src={mapSrc} alt={activeState?"Map showing "+activeState:"United States map"} onError={()=>setMapSrc(blankMap)}/><div className="mapOverlay"><div className="mapTitle"><span>Current map focus</span><strong>{activeState||"United States"}</strong></div><div className="routeLayer">{visible.slice(1).map((s,i)=>{const a=visible[i];const left=38+(a.lon+125)*1.35;const top=66-(a.lat-25)*3.2;const width=Math.max(4,Math.abs(s.lon-a.lon)*1.35);const angle=Math.atan2(-(s.lat-a.lat),(s.lon-a.lon))*180/Math.PI;return <div key={s.id} className="route" style={{left:left+"%",top:top+"%",width:width+"%",transform:"rotate("+angle+"deg)"}}/>})}</div>{visible.map(s=><button key={s.id} className={"pin "+s.confidence.toLowerCase()} style={{left:(38+(s.lon+125)*1.35)+"%",top:(66-(s.lat-25)*3.2)+"%"}} onClick={()=>setSelected(s)} title={s.place}><span/>{s.year}</button>)}</div>{latest&&<div className="mapNow"><span>{latest.year}</span><strong>{latest.place}</strong><small>{latest.person}</small></div>}</div><aside className="timeline"><div className="timelineTop"><span>Timeline</span><strong>{year}</strong></div><input type="range" min={min} max={max} value={year} onChange={e=>setYear(Number(e.target.value))}/><div className="years"><span>{min}</span><span>{max}</span></div><div className="legend"><span><i className="dot documented"/> Source-backed</span><span><i className="dot possible"/> Tree location, source needed</span></div><div className="timelineNote">The line connects recorded locations in chronological order. It does not claim the exact road, trail, or route traveled.</div></aside></section>
  <section className="migrationBottom"><div><p className="eyebrow">DOCUMENTARY TRAIL</p><h2>Every point came from the tree.</h2><p>Select an ancestor or a location to inspect what Genealogy Guide knows and what still needs evidence.</p></div><div className="stopList">{filtered.map(s=><button key={s.id} onClick={()=>{setSelected(s);setYear(s.year)}}><b>{s.year}</b><span>{s.person}</span><small>{s.place} · {s.confidence}</small></button>)}</div></section>
  {selected&&<div className="modalBack" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><p className="eyebrow">TREE LOCATION</p><h2>{selected.place}</h2><p><strong>{selected.person}</strong> · {selected.year} · {selected.state}</p><div className="sourceBox"><ShieldCheck size={17}/><div><b>{selected.confidence}</b><span>{selected.source}</span></div></div><p>{selected.notes}</p><p className="stateCode">{stateAbbr(selected.state)} · Location extracted from this family tree</p><button className="secondary" onClick={()=>setSelected(null)}>Close</button></div></div>}
 </main>
}
